### ISSUE TITLE
Login route triggers controller show method

### ISSUE THREAD

**Issue by talexand** [riverrun/openmaize-phoenix#2]
I'm trying to follow along with this repo in my own app, but I ran into a weird error. I'm using only Users for now (no Admins), but otherwise I used code from the files mentioned in the README.

Routes:
```
Generated susume app
    root_path  GET     /                    Susume.PageController :index
    user_path  GET     /users               Susume.UserController :index
    user_path  GET     /users/:id/edit      Susume.UserController :edit
    user_path  GET     /users/new           Susume.UserController :new
    user_path  GET     /users/:id           Susume.UserController :show
    user_path  POST    /users               Susume.UserController :create
    user_path  PATCH   /users/:id           Susume.UserController :update
               PUT     /users/:id           Susume.UserController :update
    user_path  DELETE  /users/:id           Susume.UserController :delete
   login_path  GET     /users/login         Susume.UserController :login
   login_path  POST    /users/login         Susume.UserController :login_user
  logout_path  GET     /users/logout        Susume.UserController :logout
```

Error log:

```
web/controllers/user_controller.ex:5: warning: unused alias Signup
Compiled web/controllers/user_controller.ex
[info] GET /users/login
[debug] Processing by Susume.UserController.show/2
  Parameters: %{"format" => "html", "id" => "login"}
  Pipelines: [:browser]
[info] Sent 400 in 5ms
[error] #PID<0.314.0> running Susume.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /users/login
** (exit) an exception was raised:
    ** (Ecto.CastError) deps/ecto/lib/ecto/repo/queryable.ex:178: value `"login"` in `where` cannot be cast to type :id in query:

from u in Susume.User,
  where: u.id == ^"login"

Error when casting value to `Susume.User.id`
        (ecto) lib/ecto/query/planner.ex:89: Ecto.Query.Planner.prepare/3
        (ecto) lib/ecto/query/planner.ex:68: Ecto.Query.Planner.query/3
        (ecto) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/4
        (ecto) lib/ecto/repo/queryable.ex:61: Ecto.Repo.Queryable.one!/4
        (susume) web/controllers/user_controller.ex:41: Susume.UserController.show/2
        (susume) web/controllers/user_controller.ex:1: Susume.UserController.phoenix_controller_pipeline/2
        (susume) lib/phoenix/router.ex:265: Susume.Router.dispatch/2
        (susume) web/router.ex:1: Susume.Router.do_call/2
```

User controller:

```elixir
defmodule Susume.UserController do
  use Susume.Web, :controller

  alias Susume.User
  alias Openmaize.Signup
  
  plug :scrub_params, "user" when action in [:create, :update]

  def index(conn, _params) do
    users = Repo.all(User)
    render(conn, "index.html", users: users)
  end

  def login(conn, _params) do
    render conn, "login.html"
  end
  
  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    # create_new(conn, Signup.create_user(user_params))

    changeset = User.changeset(%User{}, user_params)

    case Repo.insert(changeset) do
      {:ok, _user} ->
        conn

        |> put_flash(:info, "User created successfully.")
        |> redirect(to: user_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user, user_params)

    case Repo.update(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Repo.get!(User, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end
end
```

There are no users populated, but why does `GET users/login` trigger the show method?

**Comment by riverrun** [comment]
Hi,
It seems like it's trying to `show` the route /users/:id with "login" as the id, which is something I've seen before.
I need to update my version to Phoenix 0.15, which I'll do tomorrow, and then I'll be able to help you a bit more.

**Comment by riverrun** [comment]
I've added an example just using `users` and using `users/:id` (similar to your setup) [here](https://github.com/riverrun/ulmus), and it seems to be working fine.
Check out the web/router.ex file and the config/dev.exs file. Maybe there's a problem there.
Let me know how you get on.

**Comment by talexand** [comment]
Thanks for putting that up; I was able to track down my issue from your example. Router diff:

```elixir
+++ b/web/router.ex
@@ -29,14 +29,17 @@ defmodule Susume.Router do
 
     get "/", PageController, :index, as: :root
 
-    resources "/users", UserController
   end
 
   scope "/users", Susume do
+    pipe_through [:browser, :authorize]
     get "/login", UserController, :login, as: :login
     post "/login", UserController, :login_user, as: :login
     get "/logout", UserController, :logout, as: :logout
+
+    resources "/", UserController
   end
```
